sudo: required

services:
    - docker

before_install:
    - docker pull chubaofs/cfs-base:1.0

script:
    - docker/run_docker.sh -t
    - docker/run_docker.sh -l
<<<<<<< HEAD
=======

>>>>>>> 9ac6ebcd1... Sync from release-20200720
